architect:
  - meetmangukiya

install:
  - if ! pip3 -V ; then wget -O - https://bootstrap.pypa.io/get-pip.py | python3; fi
  - pip3 install -r requirements.txt

merge:
  fast-forward: only
  script: 
    - bash release.sh

decrypt:
  rultor_secrets.sh: "repo/rultor_secrets.sh.asc"

docker:
  image: "coala/rultor-python"
